CodeMark/Controllers/RecommendationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CodeMark.Models;

namespace CodeMark.Controllers
{
    public class RecommendationsController : Controller
    {
        private CodeMarkContext db = new CodeMarkContext();

        // GET: Recommendations
        public ActionResult Index()
        {
            return View(db.Recommendations.ToList());
        }

       
        // GET: Recommendations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Recommendations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Recommendation recommendation, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                using (var reader = new System.IO.BinaryReader(upload.InputStream))
                {
                    recommendation.Content = reader.ReadBytes(upload.ContentLength);
                }
                db.Recommendations.Add(recommendation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(recommendation);
        }

        // POST: Recommendations/Delete/5
        //[HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            Recommendation recommendation = db.Recommendations.Find(id);
            db.Recommendations.Remove(recommendation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public FileResult RecommendationPreview(int id)
        {
            Recommendation recommendation = db.Recommendations.Find(id);
            return File(recommendation.Content, "image/jpeg");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CodeMark/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CodeMark</title>
        @Styles.Render("~/Content/css")
        <link href="~/fonts/font-awesome/css/font-awesome.css" rel="stylesheet" />
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</head>
<body>
    <div class="recommendation-preview">
        <div class="recomm-preview-header"><i class="recomm-preview-header-close fa fa-times fa-2x"></i></div>
        <div class="recomm-preview-content">
            <img src="http://www.w3.org/html/logo/downloads/HTML5_Logo_256.png" alt="recommendation preview" />
        </div>
    </div>
    <div class="navbar  navbar-default navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CodeMark", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("O Firmie", "Index", "Home")</li>
                    <li>@Html.ActionLink("Galeria", "Gallery", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Referencje", "Index", "Recommendations")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="@*position: absolute; bottom: 0*@">
            <p>&copy; @DateTime.Now.Year - CodeMark</p>
        </footer>
    </div>

</body>
</html>